import type { Attraction, Meal } from "./route-planner-store";

export const attractionsData: Attraction[] = [
  // Beijing - 北京
  {
    id: "beijing-great-wall",
    name: "Great Wall of China",
    city: "Beijing",
    duration: 4,
    cost: 120,
    carbonFootprint: 15,
    coordinates: { lat: 40.4319, lng: 116.5704 },
    type: "Historical Site",
    image: "/beijing-great-wall.jpg",
  },
  {
    id: "beijing-forbidden-city",
    name: "Forbidden City",
    city: "Beijing",
    duration: 3,
    cost: 80,
    carbonFootprint: 5,
    coordinates: { lat: 39.9163, lng: 116.3972 },
    type: "Historical Site",
    image: "/forbidden-city.jpg",
  },
  {
    id: "beijing-temple-heaven",
    name: "Temple of Heaven",
    city: "Beijing",
    duration: 2,
    cost: 50,
    carbonFootprint: 3,
    coordinates: { lat: 39.8822, lng: 116.4066 },
    type: "Historical Site",
    image: "/temple-of-heaven.jpg",
  },
  {
    id: "beijing-summer-palace",
    name: "Summer Palace",
    city: "Beijing",
    duration: 3,
    cost: 60,
    carbonFootprint: 4,
    coordinates: { lat: 39.9999, lng: 116.2754 },
    type: "Historical Site",
    image: "/summer-palace-beijing.jpg",
  },
  {
    id: "beijing-tiananmen",
    name: "Tiananmen Square",
    city: "Beijing",
    duration: 1,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 39.9042, lng: 116.3976 },
    type: "Urban Exploration",
    image: "/tiananmen-square.jpg",
  },
  {
    id: "beijing-hutong",
    name: "Hutong Tour",
    city: "Beijing",
    duration: 2,
    cost: 100,
    carbonFootprint: 2,
    coordinates: { lat: 39.9388, lng: 116.4131 },
    type: "Cultural Experience",
    image: "/beijing-hutong.jpg",
  },
  {
    id: "beijing-lama-temple",
    name: "Lama Temple",
    city: "Beijing",
    duration: 2,
    cost: 40,
    carbonFootprint: 2,
    coordinates: { lat: 39.9485, lng: 116.4103 },
    type: "Historical Site",
    image: "/lama-temple-beijing.jpg",
  },

  // Shanghai - 上海
  {
    id: "shanghai-bund",
    name: "The Bund",
    city: "Shanghai",
    duration: 2,
    cost: 0,
    carbonFootprint: 2,
    coordinates: { lat: 31.2397, lng: 121.49 },
    type: "Urban Exploration",
    image: "/shanghai-skyline.jpg",
  },
  {
    id: "shanghai-yu-garden",
    name: "Yu Garden",
    city: "Shanghai",
    duration: 2,
    cost: 40,
    carbonFootprint: 2,
    coordinates: { lat: 31.2276, lng: 121.4926 },
    type: "Historical Site",
    image: "/yu-garden-shanghai.jpg",
  },
  {
    id: "shanghai-oriental-pearl",
    name: "Oriental Pearl Tower",
    city: "Shanghai",
    duration: 2,
    cost: 180,
    carbonFootprint: 4,
    coordinates: { lat: 31.2397, lng: 121.4997 },
    type: "Urban Exploration",
    image: "/oriental-pearl-tower.jpg",
  },
  {
    id: "shanghai-nanjing-road",
    name: "Nanjing Road",
    city: "Shanghai",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 31.2346, lng: 121.4769 },
    type: "Urban Exploration",
    image: "/nanjing-road-shanghai.jpg",
  },
  {
    id: "shanghai-french-concession",
    name: "French Concession",
    city: "Shanghai",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 31.2106, lng: 121.4442 },
    type: "Urban Exploration",
    image: "/french-concession-shanghai.jpg",
  },
  {
    id: "shanghai-jade-buddha",
    name: "Jade Buddha Temple",
    city: "Shanghai",
    duration: 1.5,
    cost: 30,
    carbonFootprint: 2,
    coordinates: { lat: 31.2443, lng: 121.4453 },
    type: "Historical Site",
    image: "/jade-buddha-temple.jpg",
  },
  {
    id: "shanghai-disney",
    name: "Shanghai Disneyland",
    city: "Shanghai",
    duration: 8,
    cost: 550,
    carbonFootprint: 20,
    coordinates: { lat: 31.1434, lng: 121.6592 },
    type: "Entertainment",
    image: "/shanghai-disneyland.jpg",
  },

  // Xi'an - 西安
  {
    id: "xian-terracotta",
    name: "Terracotta Warriors",
    city: "Xi'an",
    duration: 3,
    cost: 150,
    carbonFootprint: 8,
    coordinates: { lat: 34.3848, lng: 109.2785 },
    type: "Historical Site",
    image: "/terracotta-warriors.jpg",
  },
  {
    id: "xian-city-wall",
    name: "Xi'an City Wall",
    city: "Xi'an",
    duration: 2,
    cost: 54,
    carbonFootprint: 3,
    coordinates: { lat: 34.2655, lng: 108.954 },
    type: "Historical Site",
    image: "/xian-city-wall.jpg",
  },
  {
    id: "xian-big-wild-goose",
    name: "Big Wild Goose Pagoda",
    city: "Xi'an",
    duration: 2,
    cost: 50,
    carbonFootprint: 3,
    coordinates: { lat: 34.2192, lng: 108.9645 },
    type: "Historical Site",
    image: "/big-wild-goose-pagoda.jpg",
  },
  {
    id: "xian-muslim-quarter",
    name: "Muslim Quarter",
    city: "Xi'an",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 34.2638, lng: 108.9467 },
    type: "Cultural Experience",
    image: "/muslim-quarter-xian.jpg",
  },
  {
    id: "xian-bell-tower",
    name: "Bell Tower",
    city: "Xi'an",
    duration: 1,
    cost: 35,
    carbonFootprint: 2,
    coordinates: { lat: 34.2585, lng: 108.9486 },
    type: "Historical Site",
    image: "/bell-tower-xian.jpg",
  },

  // Guilin - 桂林
  {
    id: "guilin-li-river",
    name: "Li River Cruise",
    city: "Guilin",
    duration: 4,
    cost: 210,
    carbonFootprint: 12,
    coordinates: { lat: 25.2736, lng: 110.29 },
    type: "Natural Scenery",
    image: "/guilin-li-river.jpg",
  },
  {
    id: "guilin-reed-flute",
    name: "Reed Flute Cave",
    city: "Guilin",
    duration: 2,
    cost: 90,
    carbonFootprint: 5,
    coordinates: { lat: 25.3097, lng: 110.2644 },
    type: "Natural Scenery",
    image: "/reed-flute-cave.jpg",
  },
  {
    id: "guilin-elephant-trunk",
    name: "Elephant Trunk Hill",
    city: "Guilin",
    duration: 1.5,
    cost: 75,
    carbonFootprint: 3,
    coordinates: { lat: 25.2621, lng: 110.2821 },
    type: "Natural Scenery",
    image: "/elephant-trunk-hill-guilin.jpg",
  },
  {
    id: "guilin-seven-star",
    name: "Seven Star Park",
    city: "Guilin",
    duration: 2,
    cost: 70,
    carbonFootprint: 3,
    coordinates: { lat: 25.2799, lng: 110.3176 },
    type: "Natural Scenery",
    image: "/seven-star-park-guilin.jpg",
  },
  {
    id: "guilin-yangshuo",
    name: "Yangshuo Town",
    city: "Guilin",
    duration: 3,
    cost: 0,
    carbonFootprint: 5,
    coordinates: { lat: 24.7787, lng: 110.497 },
    type: "Urban Exploration",
    image: "/yangshuo-town.jpg",
  },

  // Chengdu - 成都
  {
    id: "chengdu-panda-base",
    name: "Chengdu Panda Base",
    city: "Chengdu",
    duration: 3,
    cost: 58,
    carbonFootprint: 4,
    coordinates: { lat: 30.7344, lng: 104.1509 },
    type: "Wildlife",
    image: "/chengdu-research-base-of-giant-panda-breeding-201907-05.jpg",
  },
  {
    id: "chengdu-jinli",
    name: "Jinli Ancient Street",
    city: "Chengdu",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 30.645, lng: 104.0491 },
    type: "Cultural Experience",
    image: "/jinli-street---chengdu-china---dsc05396.jpg",
  },
  {
    id: "chengdu-wuhou",
    name: "Wuhou Shrine",
    city: "Chengdu",
    duration: 2,
    cost: 60,
    carbonFootprint: 2,
    coordinates: { lat: 30.6443, lng: 104.0503 },
    type: "Historical Site",
    image: "/sanyi-temple-wuhou-shrine---chengdu-china---dsc05407.jpg",
  },
  {
    id: "chengdu-wide-alley",
    name: "Wide and Narrow Alleys",
    city: "Chengdu",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 30.6725, lng: 104.0603 },
    type: "Cultural Experience",
    image: "/wide-alley---宽巷子---january-2019-chengdu-sichuan.jpg",
  },
  {
    id: "chengdu-dujiangyan",
    name: "Dujiangyan Irrigation System",
    city: "Chengdu",
    duration: 3,
    cost: 90,
    carbonFootprint: 10,
    coordinates: { lat: 30.9989, lng: 103.6169 },
    type: "Historical Site",
    image: "/dujiangyan-irrigation-system-sichuan-china.jpg",
  },
  {
    id: "chengdu-mount-qingcheng",
    name: "Mount Qingcheng",
    city: "Chengdu",
    duration: 4,
    cost: 90,
    carbonFootprint: 12,
    coordinates: { lat: 31.0061, lng: 103.5611 },
    type: "Natural Scenery",
    image: "/mount-qingcheng-kina-2009-0197-4141808246.jpg",
  },
  {
    id: "chengdu-people-park",
    name: "People's Park",
    city: "Chengdu",
    duration: 1.5,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 30.6696, lng: 104.0633 },
    type: "Urban Exploration",
    image: "/boats---peoples-park---chengdu-china---dsc05378.jpg",
  },
  {
    id: "chengdu-sichuan-opera",
    name: "Sichuan Opera Performance",
    city: "Chengdu",
    duration: 2,
    cost: 150,
    carbonFootprint: 3,
    coordinates: { lat: 30.6586, lng: 104.0647 },
    type: "Cultural Experience",
    image: "/dsc07679-44544450782.jpg",
  },

  // Hangzhou - 杭州
  {
    id: "hangzhou-west-lake",
    name: "West Lake",
    city: "Hangzhou",
    duration: 3,
    cost: 0,
    carbonFootprint: 2,
    coordinates: { lat: 30.2489, lng: 120.1484 },
    type: "Natural Scenery",
    image: "/west-lake-pavilion-and-water-lilies-hangzhou-120529-1.jpg",
  },
  {
    id: "hangzhou-lingyin",
    name: "Lingyin Temple",
    city: "Hangzhou",
    duration: 2,
    cost: 75,
    carbonFootprint: 3,
    coordinates: { lat: 30.2424, lng: 120.0978 },
    type: "Historical Site",
    image: "/lingyin-si.jpg",
  },
  {
    id: "hangzhou-longjing",
    name: "Longjing Tea Village",
    city: "Hangzhou",
    duration: 2,
    cost: 50,
    carbonFootprint: 3,
    coordinates: { lat: 30.2181, lng: 120.1183 },
    type: "Cultural Experience",
    image: "/longjing-tea-village-hangzhou.jpg",
  },
  {
    id: "hangzhou-hefang",
    name: "Hefang Street",
    city: "Hangzhou",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 30.2463, lng: 120.1651 },
    type: "Cultural Experience",
    image: "/hangzhou-hefang-street-4.jpg",
  },
  {
    id: "hangzhou-leifeng-pagoda",
    name: "Leifeng Pagoda",
    city: "Hangzhou",
    duration: 1.5,
    cost: 40,
    carbonFootprint: 2,
    coordinates: { lat: 30.2314, lng: 120.1489 },
    type: "Historical Site",
    image: "/leifeng-pagoda-and-west-lake-hangzhou-120529-2.jpg",
  },
  {
    id: "hangzhou-broken-bridge",
    name: "Broken Bridge",
    city: "Hangzhou",
    duration: 1,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 30.2589, lng: 120.145 },
    type: "Natural Scenery",
    image: "/broken-bridge-hangzhou-china.jpg",
  },

  // Suzhou - 苏州
  {
    id: "suzhou-humble-garden",
    name: "Humble Administrator's Garden",
    city: "Suzhou",
    duration: 2,
    cost: 90,
    carbonFootprint: 2,
    coordinates: { lat: 31.3236, lng: 120.6284 },
    type: "Historical Site",
    image: "/humble-garden-suzhou.jpg",
  },
  {
    id: "suzhou-tiger-hill",
    name: "Tiger Hill",
    city: "Suzhou",
    duration: 2,
    cost: 80,
    carbonFootprint: 2,
    coordinates: { lat: 31.3262, lng: 120.5927 },
    type: "Historical Site",
    image: "/tiger-hill-suzhou.jpg",
  },
  {
    id: "suzhou-pingjiang-road",
    name: "Pingjiang Road",
    city: "Suzhou",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 31.3168, lng: 120.6241 },
    type: "Cultural Experience",
    image: "/pingjiang-road-suzhou.jpg",
  },
  {
    id: "suzhou-lingering-garden",
    name: "Lingering Garden",
    city: "Suzhou",
    duration: 2,
    cost: 70,
    carbonFootprint: 2,
    coordinates: { lat: 31.3203, lng: 120.5995 },
    type: "Historical Site",
    image: "/lingering-garden-suzhou.jpg",
  },
  {
    id: "suzhou-master-nets-garden",
    name: "Master of Nets Garden",
    city: "Suzhou",
    duration: 1.5,
    cost: 40,
    carbonFootprint: 1,
    coordinates: { lat: 31.2973, lng: 120.6242 },
    type: "Historical Site",
    image: "/master-nets-garden.jpg",
  },
  {
    id: "suzhou-jinji-lake",
    name: "Jinji Lake",
    city: "Suzhou",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 31.3067, lng: 120.7009 },
    type: "Natural Scenery",
    image: "/jinji-lake-suzhou.jpg",
  },
  {
    id: "suzhou-panmen-gate",
    name: "Panmen Gate",
    city: "Suzhou",
    duration: 1.5,
    cost: 40,
    carbonFootprint: 2,
    coordinates: { lat: 31.2891, lng: 120.6156 },
    type: "Historical Site",
    image: "/panmen-gate.jpg",
  },

  // Nanjing - 南京
  {
    id: "nanjing-sun-yat-sen",
    name: "Sun Yat-sen Mausoleum",
    city: "Nanjing",
    duration: 2.5,
    cost: 0,
    carbonFootprint: 3,
    coordinates: { lat: 32.0675, lng: 118.8487 },
    type: "Historical Site",
    image: "/sun-yat-sen-mausoleum-in-nanjing.jpg",
  },
  {
    id: "nanjing-memorial-hall",
    name: "Nanjing Massacre Memorial Hall",
    city: "Nanjing",
    duration: 2,
    cost: 0,
    carbonFootprint: 2,
    coordinates: { lat: 32.0431, lng: 118.7462 },
    type: "Historical Site",
    image: "/nanjing-massacre-memorial-hall.jpg",
  },
  {
    id: "nanjing-confucius-temple",
    name: "Confucius Temple (Fuzimiao)",
    city: "Nanjing",
    duration: 2,
    cost: 30,
    carbonFootprint: 2,
    coordinates: { lat: 32.0199, lng: 118.7916 },
    type: "Historical Site",
    image: "/confucius-temple-nanjing.jpg",
  },
  {
    id: "nanjing-purple-mountain",
    name: "Purple Mountain",
    city: "Nanjing",
    duration: 3,
    cost: 0,
    carbonFootprint: 3,
    coordinates: { lat: 32.0675, lng: 118.8487 },
    type: "Natural Scenery",
    image: "/purple-mountain-nanjing-scenic-view.jpg",
  },
  {
    id: "nanjing-ming-wall",
    name: "Ming City Wall",
    city: "Nanjing",
    duration: 2,
    cost: 50,
    carbonFootprint: 2,
    coordinates: { lat: 32.0433, lng: 118.7795 },
    type: "Historical Site",
    image: "/nanjing-ming-dynasty-city-wall.jpg",
  },
  {
    id: "nanjing-xuanwu-lake",
    name: "Xuanwu Lake",
    city: "Nanjing",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 32.0686, lng: 118.7956 },
    type: "Natural Scenery",
    image: "/xuanwu-lake-nanjing.jpg",
  },
  {
    id: "nanjing-presidential-palace",
    name: "Presidential Palace",
    city: "Nanjing",
    duration: 2,
    cost: 40,
    carbonFootprint: 2,
    coordinates: { lat: 32.0434, lng: 118.797 },
    type: "Historical Site",
    image: "/nanjing-presidential-palace.jpg",
  },
  {
    id: "nanjing-qinhuai-river",
    name: "Qinhuai River Night Cruise",
    city: "Nanjing",
    duration: 1.5,
    cost: 80,
    carbonFootprint: 4,
    coordinates: { lat: 32.0196, lng: 118.7909 },
    type: "Cultural Experience",
    image: "/qinhuai-river-night-cruise-nanjing.jpg",
  },

  // Wuzhen - 乌镇
  {
    id: "wuzhen-east-scenic",
    name: "Wuzhen East Scenic Area",
    city: "Wuzhen",
    duration: 3,
    cost: 120,
    carbonFootprint: 3,
    coordinates: { lat: 30.7456, lng: 120.4856 },
    type: "Cultural Experience",
    image: "/wuzhen-water-town.jpg",
  },
  {
    id: "wuzhen-west-scenic",
    name: "Wuzhen West Scenic Area",
    city: "Wuzhen",
    duration: 3,
    cost: 150,
    carbonFootprint: 3,
    coordinates: { lat: 30.7456, lng: 120.4856 },
    type: "Cultural Experience",
    image: "/wuzhen-west-scenic.jpg",
  },
  {
    id: "wuzhen-ancient-bridge",
    name: "Ancient Bridge",
    city: "Wuzhen",
    duration: 1,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 30.7456, lng: 120.4856 },
    type: "Historical Site",
    image: "/wuzhen-bridge.jpg",
  },
  {
    id: "wuzhen-water-town",
    name: "Water Town Cruise",
    city: "Wuzhen",
    duration: 2,
    cost: 60,
    carbonFootprint: 2,
    coordinates: { lat: 30.7456, lng: 120.4856 },
    type: "Cultural Experience",
    image: "/wuzhen-canal.jpg",
  },
  {
    id: "wuzhen-folk-customs",
    name: "Folk Customs Museum",
    city: "Wuzhen",
    duration: 1.5,
    cost: 40,
    carbonFootprint: 1,
    coordinates: { lat: 30.7456, lng: 120.4856 },
    type: "Cultural Experience",
    image: "/wuzhen-museum.jpg",
  },

  // Guangzhou - 广州
  {
    id: "guangzhou-canton-tower",
    name: "Canton Tower",
    city: "Guangzhou",
    duration: 2,
    cost: 150,
    carbonFootprint: 4,
    coordinates: { lat: 23.1064, lng: 113.3245 },
    type: "Urban Exploration",
    image: "/guangzhou-canton-tower.jpg",
  },
  {
    id: "guangzhou-temple-six-banyans",
    name: "Temple of Six Banyan Trees",
    city: "Guangzhou",
    duration: 1.5,
    cost: 20,
    carbonFootprint: 2,
    coordinates: { lat: 23.1304, lng: 113.2604 },
    type: "Historical Site",
    image: "/guangzhou-six-banyan-temple.jpg",
  },
  {
    id: "guangzhou-shamian-island",
    name: "Shamian Island",
    city: "Guangzhou",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 23.1089, lng: 113.2434 },
    type: "Urban Exploration",
    image: "/guangzhou-shamian-island.jpg",
  },
  {
    id: "guangzhou-yuexiu-park",
    name: "Yuexiu Park",
    city: "Guangzhou",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 23.1394, lng: 113.2704 },
    type: "Natural Scenery",
    image: "/guangzhou-yuexiu-park.jpg",
  },
  {
    id: "guangzhou-pearl-river",
    name: "Pearl River Night Cruise",
    city: "Guangzhou",
    duration: 1.5,
    cost: 80,
    carbonFootprint: 4,
    coordinates: { lat: 23.1064, lng: 113.3245 },
    type: "Cultural Experience",
    image: "/guangzhou-pearl-river.jpg",
  },
  {
    id: "guangzhou-chen-ancestral-temple",
    name: "Chen Ancestral Temple",
    city: "Guangzhou",
    duration: 1.5,
    cost: 10,
    carbonFootprint: 1,
    coordinates: { lat: 23.1304, lng: 113.2604 },
    type: "Historical Site",
    image: "/guangzhou-chen-temple.jpg",
  },

  // Hong Kong - 香港
  {
    id: "hongkong-victoria-peak",
    name: "Victoria Peak",
    city: "Hong Kong",
    duration: 2,
    cost: 88,
    carbonFootprint: 3,
    coordinates: { lat: 22.2719, lng: 114.1499 },
    type: "Natural Scenery",
    image: "/hongkong-victoria-peak.jpg",
  },
  {
    id: "hongkong-star-ferry",
    name: "Star Ferry",
    city: "Hong Kong",
    duration: 0.5,
    cost: 5,
    carbonFootprint: 1,
    coordinates: { lat: 22.2864, lng: 114.1581 },
    type: "Cultural Experience",
    image: "/hongkong-star-ferry.jpg",
  },
  {
    id: "hongkong-disneyland",
    name: "Hong Kong Disneyland",
    city: "Hong Kong",
    duration: 8,
    cost: 639,
    carbonFootprint: 20,
    coordinates: { lat: 22.3136, lng: 114.0416 },
    type: "Entertainment",
    image: "/hongkong-disneyland.jpg",
  },
  {
    id: "hongkong-big-buddha",
    name: "Tian Tan Buddha",
    city: "Hong Kong",
    duration: 2,
    cost: 0,
    carbonFootprint: 5,
    coordinates: { lat: 22.2539, lng: 113.9047 },
    type: "Historical Site",
    image: "/hongkong-big-buddha.jpg",
  },
  {
    id: "hongkong-temple-street",
    name: "Temple Street Night Market",
    city: "Hong Kong",
    duration: 2,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 22.3056, lng: 114.1703 },
    type: "Cultural Experience",
    image: "/hongkong-temple-street.jpg",
  },
  {
    id: "hongkong-ocean-park",
    name: "Ocean Park",
    city: "Hong Kong",
    duration: 6,
    cost: 498,
    carbonFootprint: 15,
    coordinates: { lat: 22.2486, lng: 114.1744 },
    type: "Entertainment",
    image: "/hongkong-ocean-park.jpg",
  },

  // Macau - 澳门
  {
    id: "macau-ruins-st-paul",
    name: "Ruins of St. Paul's",
    city: "Macau",
    duration: 1,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 22.1978, lng: 113.5408 },
    type: "Historical Site",
    image: "/macau-ruins-st-paul.jpg",
  },
  {
    id: "macau-venetian",
    name: "The Venetian Macao",
    city: "Macau",
    duration: 3,
    cost: 0,
    carbonFootprint: 5,
    coordinates: { lat: 22.1444, lng: 113.5581 },
    type: "Entertainment",
    image: "/macau-venetian.jpg",
  },
  {
    id: "macau-a-ma-temple",
    name: "A-Ma Temple",
    city: "Macau",
    duration: 1,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 22.1867, lng: 113.5308 },
    type: "Historical Site",
    image: "/macau-a-ma-temple.jpg",
  },
  {
    id: "macau-senado-square",
    name: "Senado Square",
    city: "Macau",
    duration: 1,
    cost: 0,
    carbonFootprint: 1,
    coordinates: { lat: 22.1933, lng: 113.5408 },
    type: "Urban Exploration",
    image: "/macau-senado-square.jpg",
  },
  {
    id: "macau-macau-tower",
    name: "Macau Tower",
    city: "Macau",
    duration: 1.5,
    cost: 135,
    carbonFootprint: 3,
    coordinates: { lat: 22.2133, lng: 113.5439 },
    type: "Urban Exploration",
    image: "/macau-tower.jpg",
  },
];

export const mealsData: Meal[] = [
  // Beijing Cuisine
  {
    id: "beijing-peking-duck",
    name: "Peking Duck",
    city: "Beijing",
    cost: 200,
    carbonFootprint: 8,
    type: "Fine Dining",
    cuisine: "Beijing Cuisine",
    image: "/food-peking-duck.jpg",
  },
  {
    id: "beijing-jiaozi",
    name: "Beijing Dumplings (Jiaozi)",
    city: "Beijing",
    cost: 40,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Beijing Cuisine",
    image: "/food-dumplings.jpg",
  },
  {
    id: "beijing-zhajiangmian",
    name: "Zhajiangmian (Noodles)",
    city: "Beijing",
    cost: 30,
    carbonFootprint: 2,
    type: "Street Food",
    cuisine: "Beijing Cuisine",
    image: "/food-zhajiangmian.jpg",
  },
  {
    id: "beijing-hotpot",
    name: "Beijing Hotpot",
    city: "Beijing",
    cost: 120,
    carbonFootprint: 6,
    type: "Local Restaurant",
    cuisine: "Beijing Cuisine",
    image: "/food-beijing-hotpot.jpg",
  },

  // Shanghai Cuisine
  {
    id: "shanghai-xiaolongbao",
    name: "Xiaolongbao (Soup Dumplings)",
    city: "Shanghai",
    cost: 50,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Shanghai Cuisine",
    image: "/food-xiaolongbao.jpg",
  },
  {
    id: "shanghai-shengjianbao",
    name: "Shengjianbao (Pan-fried Buns)",
    city: "Shanghai",
    cost: 25,
    carbonFootprint: 2,
    type: "Street Food",
    cuisine: "Shanghai Cuisine",
    image: "/food-shengjianbao.jpg",
  },
  {
    id: "shanghai-hairy-crab",
    name: "Shanghai Hairy Crab",
    city: "Shanghai",
    cost: 300,
    carbonFootprint: 10,
    type: "Fine Dining",
    cuisine: "Shanghai Cuisine",
    image: "/food-hairy-crab.jpg",
  },
  {
    id: "shanghai-braised-pork",
    name: "Hongshao Rou (Braised Pork)",
    city: "Shanghai",
    cost: 80,
    carbonFootprint: 5,
    type: "Local Restaurant",
    cuisine: "Shanghai Cuisine",
    image: "/food-braised-pork.jpg",
  },

  // Xi'an Cuisine
  {
    id: "xian-biang-biang",
    name: "Biang Biang Noodles",
    city: "Xi'an",
    cost: 35,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Shaanxi Cuisine",
    image: "/food-biang-biang.jpg",
  },
  {
    id: "xian-roujiamo",
    name: "Roujiamo (Chinese Burger)",
    city: "Xi'an",
    cost: 20,
    carbonFootprint: 3,
    type: "Street Food",
    cuisine: "Shaanxi Cuisine",
    image: "/food-roujiamo.jpg",
  },
  {
    id: "xian-yangrou-paomo",
    name: "Yangrou Paomo (Lamb Soup)",
    city: "Xi'an",
    cost: 45,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Shaanxi Cuisine",
    image: "/food-yangrou-paomo.jpg",
  },
  {
    id: "xian-liangpi",
    name: "Liangpi (Cold Noodles)",
    city: "Xi'an",
    cost: 15,
    carbonFootprint: 1,
    type: "Street Food",
    cuisine: "Shaanxi Cuisine",
    image: "/food-liangpi.jpg",
  },

  // Guilin Cuisine
  {
    id: "guilin-rice-noodles",
    name: "Guilin Rice Noodles",
    city: "Guilin",
    cost: 25,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Guangxi Cuisine",
    image: "/food-guilin-noodles.jpg",
  },
  {
    id: "guilin-beer-fish",
    name: "Yangshuo Beer Fish",
    city: "Guilin",
    cost: 80,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Guangxi Cuisine",
    image: "/food-beer-fish.jpg",
  },
  {
    id: "guilin-stuffed-snails",
    name: "Stuffed River Snails",
    city: "Guilin",
    cost: 35,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Guangxi Cuisine",
    image: "/food-stuffed-snails.jpg",
  },

  // Chengdu Cuisine
  {
    id: "chengdu-hotpot",
    name: "Chengdu Spicy Hotpot",
    city: "Chengdu",
    cost: 100,
    carbonFootprint: 6,
    type: "Local Restaurant",
    cuisine: "Sichuan Cuisine",
    image: "/food-chengdu-hotpot.jpg",
  },
  {
    id: "chengdu-mapo-tofu",
    name: "Mapo Tofu",
    city: "Chengdu",
    cost: 40,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Sichuan Cuisine",
    image: "/food-mapo-tofu.jpg",
  },
  {
    id: "chengdu-dan-dan",
    name: "Dan Dan Noodles",
    city: "Chengdu",
    cost: 30,
    carbonFootprint: 2,
    type: "Street Food",
    cuisine: "Sichuan Cuisine",
    image: "/food-dan-dan-noodles.jpg",
  },
  {
    id: "chengdu-kung-pao",
    name: "Kung Pao Chicken",
    city: "Chengdu",
    cost: 50,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Sichuan Cuisine",
    image: "/food-kung-pao-chicken.jpg",
  },
  {
    id: "chengdu-fuqi-feipian",
    name: "Fuqi Feipian (Beef Slices)",
    city: "Chengdu",
    cost: 45,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Sichuan Cuisine",
    image: "/food-fuqi-feipian.jpg",
  },

  // Hangzhou Cuisine
  {
    id: "hangzhou-west-lake-fish",
    name: "West Lake Fish in Vinegar",
    city: "Hangzhou",
    cost: 120,
    carbonFootprint: 5,
    type: "Fine Dining",
    cuisine: "Zhejiang Cuisine",
    image: "/food-west-lake-fish.jpg",
  },
  {
    id: "hangzhou-dongpo-pork",
    name: "Dongpo Pork",
    city: "Hangzhou",
    cost: 80,
    carbonFootprint: 5,
    type: "Local Restaurant",
    cuisine: "Zhejiang Cuisine",
    image: "/food-dongpo-pork.jpg",
  },
  {
    id: "hangzhou-longjing-shrimp",
    name: "Longjing Tea Shrimp",
    city: "Hangzhou",
    cost: 90,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Zhejiang Cuisine",
    image: "/food-longjing-shrimp.jpg",
  },

  // Suzhou Cuisine
  {
    id: "suzhou-squirrel-fish",
    name: "Squirrel-shaped Mandarin Fish",
    city: "Suzhou",
    cost: 100,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Jiangsu Cuisine",
    image: "/food-squirrel-fish.jpg",
  },
  {
    id: "suzhou-biluochun-tea",
    name: "Biluochun Tea Experience",
    city: "Suzhou",
    cost: 60,
    carbonFootprint: 1,
    type: "Tea House",
    cuisine: "Jiangsu Cuisine",
    image: "/food-biluochun-tea.jpg",
  },
  {
    id: "suzhou-sweet-sour-ribs",
    name: "Sweet and Sour Ribs",
    city: "Suzhou",
    cost: 70,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Jiangsu Cuisine",
    image: "/food-sweet-sour-ribs.jpg",
  },

  // Nanjing Cuisine
  {
    id: "nanjing-salted-duck",
    name: "Nanjing Salted Duck",
    city: "Nanjing",
    cost: 60,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Jiangsu Cuisine",
    image: "/nanjing-salted-duck-dish.jpg",
  },
  {
    id: "nanjing-duck-blood-soup",
    name: "Duck Blood Soup",
    city: "Nanjing",
    cost: 35,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Jiangsu Cuisine",
    image: "/nanjing-duck-blood-soup.jpg",
  },
  {
    id: "nanjing-steamed-buns",
    name: "Nanjing Soup Dumplings",
    city: "Nanjing",
    cost: 40,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Jiangsu Cuisine",
    image: "/nanjing-soup-dumplings.jpg",
  },
  {
    id: "nanjing-beef-pot-stickers",
    name: "Beef Pot Stickers",
    city: "Nanjing",
    cost: 30,
    carbonFootprint: 3,
    type: "Street Food",
    cuisine: "Jiangsu Cuisine",
    image: "/nanjing-beef-pot-stickers.jpg",
  },

  // Wuzhen Cuisine
  {
    id: "wuzhen-dongpo-pork",
    name: "Wuzhen Dongpo Pork",
    city: "Wuzhen",
    cost: 80,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Zhejiang Cuisine",
    image: "/food-wuzhen-dongpo-pork.jpg",
  },
  {
    id: "wuzhen-white-fish",
    name: "Steamed White Fish",
    city: "Wuzhen",
    cost: 90,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Zhejiang Cuisine",
    image: "/food-wuzhen-fish.jpg",
  },
  {
    id: "wuzhen-wine-chicken",
    name: "Wuzhen Wine Chicken",
    city: "Wuzhen",
    cost: 60,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Zhejiang Cuisine",
    image: "/food-wuzhen-chicken.jpg",
  },

  // Guangzhou Cuisine
  {
    id: "guangzhou-dim-sum",
    name: "Cantonese Dim Sum",
    city: "Guangzhou",
    cost: 80,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Cantonese Cuisine",
    image: "/food-guangzhou-dim-sum.jpg",
  },
  {
    id: "guangzhou-roast-goose",
    name: "Roast Goose",
    city: "Guangzhou",
    cost: 120,
    carbonFootprint: 5,
    type: "Local Restaurant",
    cuisine: "Cantonese Cuisine",
    image: "/food-guangzhou-goose.jpg",
  },
  {
    id: "guangzhou-wonton-noodles",
    name: "Wonton Noodles",
    city: "Guangzhou",
    cost: 35,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Cantonese Cuisine",
    image: "/food-guangzhou-wonton.jpg",
  },
  {
    id: "guangzhou-claypot-rice",
    name: "Claypot Rice",
    city: "Guangzhou",
    cost: 45,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Cantonese Cuisine",
    image: "/food-guangzhou-claypot.jpg",
  },

  // Hong Kong Cuisine
  {
    id: "hongkong-char-siu",
    name: "Char Siu (BBQ Pork)",
    city: "Hong Kong",
    cost: 60,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Cantonese Cuisine",
    image: "/food-hongkong-char-siu.jpg",
  },
  {
    id: "hongkong-egg-tart",
    name: "Hong Kong Egg Tart",
    city: "Hong Kong",
    cost: 15,
    carbonFootprint: 1,
    type: "Street Food",
    cuisine: "Cantonese Cuisine",
    image: "/food-hongkong-egg-tart.jpg",
  },
  {
    id: "hongkong-milk-tea",
    name: "Hong Kong Style Milk Tea",
    city: "Hong Kong",
    cost: 20,
    carbonFootprint: 1,
    type: "Street Food",
    cuisine: "Cantonese Cuisine",
    image: "/food-hongkong-milk-tea.jpg",
  },
  {
    id: "hongkong-wonton-soup",
    name: "Wonton Soup",
    city: "Hong Kong",
    cost: 40,
    carbonFootprint: 2,
    type: "Local Restaurant",
    cuisine: "Cantonese Cuisine",
    image: "/food-hongkong-wonton-soup.jpg",
  },

  // Macau Cuisine
  {
    id: "macau-egg-tart",
    name: "Macau Egg Tart",
    city: "Macau",
    cost: 12,
    carbonFootprint: 1,
    type: "Street Food",
    cuisine: "Macanese Cuisine",
    image: "/food-macau-egg-tart.jpg",
  },
  {
    id: "macau-african-chicken",
    name: "African Chicken",
    city: "Macau",
    cost: 85,
    carbonFootprint: 4,
    type: "Local Restaurant",
    cuisine: "Macanese Cuisine",
    image: "/food-macau-chicken.jpg",
  },
  {
    id: "macau-pork-chop-bun",
    name: "Pork Chop Bun",
    city: "Macau",
    cost: 25,
    carbonFootprint: 2,
    type: "Street Food",
    cuisine: "Macanese Cuisine",
    image: "/food-macau-pork-bun.jpg",
  },
  {
    id: "macau-minchi",
    name: "Minchi (Macanese Hash)",
    city: "Macau",
    cost: 55,
    carbonFootprint: 3,
    type: "Local Restaurant",
    cuisine: "Macanese Cuisine",
    image: "/food-macau-minchi.jpg",
  },
];
