import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import type { Language } from "./translations";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const ATTRACTION_NAME_MAP: Record<Language, Record<string, string>> = {
  en: {
    "beijing-great-wall": "Great Wall of China",
    "beijing-forbidden-city": "Forbidden City",
    "beijing-temple-heaven": "Temple of Heaven",
    "beijing-summer-palace": "Summer Palace",
    "beijing-tiananmen": "Tiananmen Square",
    "beijing-hutong": "Hutong Tour",
    "beijing-lama-temple": "Lama Temple",
    "shanghai-bund": "The Bund",
    "shanghai-yu-garden": "Yu Garden",
    "shanghai-oriental-pearl": "Oriental Pearl Tower",
    "shanghai-nanjing-road": "Nanjing Road",
    "shanghai-french-concession": "French Concession",
    "shanghai-jade-buddha": "Jade Buddha Temple",
    "shanghai-disney": "Shanghai Disneyland",
    "xian-terracotta": "Terracotta Warriors",
    "xian-city-wall": "Xi'an City Wall",
    "xian-big-wild-goose": "Big Wild Goose Pagoda",
    "xian-muslim-quarter": "Muslim Quarter",
    "xian-bell-tower": "Bell Tower",
    "guilin-li-river": "Li River Cruise",
    "guilin-reed-flute": "Reed Flute Cave",
    "guilin-elephant-trunk": "Elephant Trunk Hill",
    "guilin-seven-star": "Seven Star Park",
    "guilin-yangshuo": "Yangshuo Town",
    "chengdu-panda-base": "Chengdu Panda Base",
    "chengdu-jinli": "Jinli Ancient Street",
    "chengdu-wuhou": "Wuhou Shrine",
    "chengdu-wide-alley": "Wide and Narrow Alleys",
    "chengdu-dujiangyan": "Dujiangyan Irrigation System",
    "chengdu-mount-qingcheng": "Mount Qingcheng",
    "chengdu-people-park": "People's Park",
    "chengdu-sichuan-opera": "Sichuan Opera Performance",
    "hangzhou-west-lake": "West Lake",
    "hangzhou-lingyin": "Lingyin Temple",
    "hangzhou-longjing": "Longjing Tea Village",
    "hangzhou-hefang": "Hefang Street",
    "hangzhou-leifeng-pagoda": "Leifeng Pagoda",
    "hangzhou-broken-bridge": "Broken Bridge",
    "suzhou-humble-garden": "Humble Administrator's Garden",
    "suzhou-tiger-hill": "Tiger Hill",
    "suzhou-pingjiang-road": "Pingjiang Road",
    "suzhou-lingering-garden": "Lingering Garden",
    "suzhou-master-nets-garden": "Master of Nets Garden",
    "suzhou-jinji-lake": "Jinji Lake",
    "suzhou-panmen-gate": "Panmen Gate",
    "nanjing-sun-yat-sen": "Sun Yat-sen Mausoleum",
    "nanjing-memorial-hall": "Nanjing Massacre Memorial Hall",
    "nanjing-confucius-temple": "Confucius Temple (Fuzimiao)",
    "nanjing-purple-mountain": "Purple Mountain",
    "nanjing-ming-wall": "Ming City Wall",
    "nanjing-xuanwu-lake": "Xuanwu Lake",
    "nanjing-presidential-palace": "Presidential Palace",
    "nanjing-qinhuai-river": "Qinhuai River Night Cruise",
    "wuzhen-east-scenic": "Wuzhen East Scenic Area",
    "wuzhen-west-scenic": "Wuzhen West Scenic Area",
    "wuzhen-ancient-bridge": "Ancient Bridge",
    "wuzhen-water-town": "Water Town Cruise",
    "wuzhen-folk-customs": "Folk Customs Museum",
    "guangzhou-canton-tower": "Canton Tower",
    "guangzhou-temple-six-banyans": "Temple of Six Banyan Trees",
    "guangzhou-shamian-island": "Shamian Island",
    "guangzhou-yuexiu-park": "Yuexiu Park",
    "guangzhou-pearl-river": "Pearl River Night Cruise",
    "guangzhou-chen-ancestral-temple": "Chen Ancestral Temple",
    "hongkong-victoria-peak": "Victoria Peak",
    "hongkong-star-ferry": "Star Ferry",
    "hongkong-disneyland": "Hong Kong Disneyland",
    "hongkong-big-buddha": "Tian Tan Buddha",
    "hongkong-temple-street": "Temple Street Night Market",
    "hongkong-ocean-park": "Ocean Park",
    "macau-ruins-st-paul": "Ruins of St. Paul's",
    "macau-venetian": "The Venetian Macao",
    "macau-a-ma-temple": "A-Ma Temple",
    "macau-senado-square": "Senado Square",
    "macau-macau-tower": "Macau Tower",
  },
  zh: {
    "beijing-great-wall": "长城",
    "beijing-forbidden-city": "紫禁城",
    "beijing-temple-heaven": "天坛",
    "beijing-summer-palace": "颐和园",
    "beijing-tiananmen": "天安门广场",
    "beijing-hutong": "胡同游览",
    "beijing-lama-temple": "雍和宫",
    "shanghai-bund": "外滩",
    "shanghai-yu-garden": "豫园",
    "shanghai-oriental-pearl": "东方明珠塔",
    "shanghai-nanjing-road": "南京路",
    "shanghai-french-concession": "法租界",
    "shanghai-jade-buddha": "玉佛禅寺",
    "shanghai-disney": "上海迪士尼乐园",
    "xian-terracotta": "兵马俑",
    "xian-city-wall": "西安城墙",
    "xian-big-wild-goose": "大雁塔",
    "xian-muslim-quarter": "回民街",
    "xian-bell-tower": "钟楼",
    "guilin-li-river": "漓江游船",
    "guilin-reed-flute": "芦笛岩",
    "guilin-elephant-trunk": "象鼻山",
    "guilin-seven-star": "七星公园",
    "guilin-yangshuo": "阳朔古镇",
    "chengdu-panda-base": "成都大熊猫繁育研究基地",
    "chengdu-jinli": "锦里古街",
    "chengdu-wuhou": "武侯祠",
    "chengdu-wide-alley": "宽窄巷子",
    "chengdu-dujiangyan": "都江堰水利工程",
    "chengdu-mount-qingcheng": "青城山",
    "chengdu-people-park": "人民公园",
    "chengdu-sichuan-opera": "川剧表演",
    "hangzhou-west-lake": "西湖",
    "hangzhou-lingyin": "灵隐寺",
    "hangzhou-longjing": "龙井茶村",
    "hangzhou-hefang": "河坊街",
    "hangzhou-leifeng-pagoda": "雷峰塔",
    "hangzhou-broken-bridge": "断桥",
    "suzhou-humble-garden": "拙政园",
    "suzhou-tiger-hill": "虎丘",
    "suzhou-pingjiang-road": "平江路",
    "suzhou-lingering-garden": "留园",
    "suzhou-master-nets-garden": "网师园",
    "suzhou-jinji-lake": "金鸡湖",
    "suzhou-panmen-gate": "盘门",
    "nanjing-sun-yat-sen": "中山陵",
    "nanjing-memorial-hall": "南京大屠杀遇难者纪念馆",
    "nanjing-confucius-temple": "夫子庙",
    "nanjing-purple-mountain": "紫金山",
    "nanjing-ming-wall": "明城墙",
    "nanjing-xuanwu-lake": "玄武湖",
    "nanjing-presidential-palace": "总统府",
    "nanjing-qinhuai-river": "秦淮河夜游",
    "wuzhen-east-scenic": "乌镇东栅景区",
    "wuzhen-west-scenic": "乌镇西栅景区",
    "wuzhen-ancient-bridge": "古桥",
    "wuzhen-water-town": "水乡游船",
    "wuzhen-folk-customs": "民俗博物馆",
    "guangzhou-canton-tower": "广州塔",
    "guangzhou-temple-six-banyans": "六榕寺",
    "guangzhou-shamian-island": "沙面岛",
    "guangzhou-yuexiu-park": "越秀公园",
    "guangzhou-pearl-river": "珠江夜游",
    "guangzhou-chen-ancestral-temple": "陈家祠",
    "hongkong-victoria-peak": "太平山顶",
    "hongkong-star-ferry": "天星小轮",
    "hongkong-disneyland": "香港迪士尼乐园",
    "hongkong-big-buddha": "天坛大佛",
    "hongkong-temple-street": "庙街夜市",
    "hongkong-ocean-park": "海洋公园",
    "macau-ruins-st-paul": "大三巴牌坊",
    "macau-venetian": "澳门威尼斯人",
    "macau-a-ma-temple": "妈阁庙",
    "macau-senado-square": "议事亭前地",
    "macau-macau-tower": "澳门旅游塔",
  },
  fr: {
    "beijing-great-wall": "Grande Muraille de Chine",
    "beijing-forbidden-city": "Cité Interdite",
    "beijing-temple-heaven": "Temple du Ciel",
    "beijing-summer-palace": "Palais d'Été",
    "beijing-tiananmen": "Place Tian'anmen",
    "beijing-hutong": "Visite des Hutongs",
    "beijing-lama-temple": "Temple des Lamas (Yonghe)",
    "shanghai-bund": "Le Bund",
    "shanghai-yu-garden": "Jardin Yuyuan",
    "shanghai-oriental-pearl": "Tour de la Perle Orientale",
    "shanghai-nanjing-road": "Rue de Nankin",
    "shanghai-french-concession": "Concession Française",
    "shanghai-jade-buddha": "Temple du Bouddha de Jade",
    "shanghai-disney": "Shanghai Disneyland",
    "xian-terracotta": "Guerriers de Terre Cuite",
    "xian-city-wall": "Muraille de Xi'an",
    "xian-big-wild-goose": "Pagode de la Grande Oie Sauvage",
    "xian-muslim-quarter": "Quartier Musulman",
    "xian-bell-tower": "Tour de la Cloche",
    "guilin-li-river": "Croisière sur la rivière Li",
    "guilin-reed-flute": "Grotte de la Flûte de Roseau",
    "guilin-elephant-trunk": "Colline de la Trompe d'Éléphant",
    "guilin-seven-star": "Parc des Sept Étoiles",
    "guilin-yangshuo": "Ville de Yangshuo",
    "chengdu-panda-base": "Base des Pandas Géants de Chengdu",
    "chengdu-jinli": "Rue Ancienne Jinli",
    "chengdu-wuhou": "Sanctuaire de Wuhou",
    "chengdu-wide-alley": "Allées Larges et Étroites",
    "chengdu-dujiangyan": "Système d’irrigation de Dujiangyan",
    "chengdu-mount-qingcheng": "Mont Qingcheng",
    "chengdu-people-park": "Parc du Peuple",
    "chengdu-sichuan-opera": "Spectacle d’Opéra du Sichuan",
    "hangzhou-west-lake": "Lac de l'Ouest",
    "hangzhou-lingyin": "Temple de Lingyin",
    "hangzhou-longjing": "Village du Thé Longjing",
    "hangzhou-hefang": "Rue Hefang",
    "hangzhou-leifeng-pagoda": "Pagode Leifeng",
    "hangzhou-broken-bridge": "Pont Brisé",
    "suzhou-humble-garden": "Jardin de l’Humble Administrateur",
    "suzhou-tiger-hill": "Colline du Tigre",
    "suzhou-pingjiang-road": "Rue Pingjiang",
    "suzhou-lingering-garden": "Jardin Liu",
    "suzhou-master-nets-garden": "Jardin du Maître des Filets",
    "suzhou-jinji-lake": "Lac Jinji",
    "suzhou-panmen-gate": "Porte Panmen",
    "nanjing-sun-yat-sen": "Mausolée de Sun Yat-sen",
    "nanjing-memorial-hall": "Mémorial du Massacre de Nankin",
    "nanjing-confucius-temple": "Temple de Confucius (Fuzimiao)",
    "nanjing-purple-mountain": "Montagne Pourpre",
    "nanjing-ming-wall": "Remparts de la Dynastie Ming",
    "nanjing-xuanwu-lake": "Lac Xuanwu",
    "nanjing-presidential-palace": "Palais Présidentiel",
    "nanjing-qinhuai-river": "Croisière nocturne sur la rivière Qinhuai",
    "wuzhen-east-scenic": "Zone Scénique Est de Wuzhen",
    "wuzhen-west-scenic": "Zone Scénique Ouest de Wuzhen",
    "wuzhen-ancient-bridge": "Pont Ancien",
    "wuzhen-water-town": "Croisière sur la Ville d'Eau",
    "wuzhen-folk-customs": "Musée des Coutumes Populaires",
    "guangzhou-canton-tower": "Tour de Canton",
    "guangzhou-temple-six-banyans": "Temple des Six Banians",
    "guangzhou-shamian-island": "Île de Shamian",
    "guangzhou-yuexiu-park": "Parc Yuexiu",
    "guangzhou-pearl-river": "Croisière nocturne sur la rivière des Perles",
    "guangzhou-chen-ancestral-temple": "Temple Ancestral Chen",
    "hongkong-victoria-peak": "Le Pic Victoria",
    "hongkong-star-ferry": "Star Ferry",
    "hongkong-disneyland": "Hong Kong Disneyland",
    "hongkong-big-buddha": "Bouddha Tian Tan",
    "hongkong-temple-street": "Marché nocturne de Temple Street",
    "hongkong-ocean-park": "Ocean Park",
    "macau-ruins-st-paul": "Ruines de Saint-Paul",
    "macau-venetian": "Le Venetian Macao",
    "macau-a-ma-temple": "Temple A-Ma",
    "macau-senado-square": "Place du Sénat",
    "macau-macau-tower": "Tour de Macao",
  },
  es: {
    "beijing-great-wall": "Gran Muralla China",
    "beijing-forbidden-city": "Ciudad Prohibida",
    "beijing-temple-heaven": "Templo del Cielo",
    "beijing-summer-palace": "Palacio de Verano",
    "beijing-tiananmen": "Plaza de Tiananmén",
    "beijing-hutong": "Recorrido por los hutongs",
    "beijing-lama-temple": "Templo de los Lamas (Yonghe)",
    "shanghai-bund": "El Bund",
    "shanghai-yu-garden": "Jardín Yuyuan",
    "shanghai-oriental-pearl": "Torre Perla Oriental",
    "shanghai-nanjing-road": "Calle Nanjing",
    "shanghai-french-concession": "Concesión Francesa",
    "shanghai-jade-buddha": "Templo del Buda de Jade",
    "shanghai-disney": "Shanghai Disneyland",
    "xian-terracotta": "Guerreros de Terracota",
    "xian-city-wall": "Muralla de Xi’an",
    "xian-big-wild-goose": "Pagoda del Ganso Salvaje",
    "xian-muslim-quarter": "Barrio Musulmán",
    "xian-bell-tower": "Torre de la Campana",
    "guilin-li-river": "Crucero por el río Li",
    "guilin-reed-flute": "Cueva de la Flauta de Caña",
    "guilin-elephant-trunk": "Colina Trompa de Elefante",
    "guilin-seven-star": "Parque de las Siete Estrellas",
    "guilin-yangshuo": "Ciudad de Yangshuo",
    "chengdu-panda-base": "Base de Pandas de Chengdu",
    "chengdu-jinli": "Calle Antigua Jinli",
    "chengdu-wuhou": "Santuario Wuhou",
    "chengdu-wide-alley": "Callejones Anchos y Estrechos",
    "chengdu-dujiangyan": "Sistema de Irrigación de Dujiangyan",
    "chengdu-mount-qingcheng": "Monte Qingcheng",
    "chengdu-people-park": "Parque del Pueblo",
    "chengdu-sichuan-opera": "Espectáculo de Ópera de Sichuan",
    "hangzhou-west-lake": "Lago del Oeste",
    "hangzhou-lingyin": "Templo Lingyin",
    "hangzhou-longjing": "Pueblo del Té Longjing",
    "hangzhou-hefang": "Calle Hefang",
    "hangzhou-leifeng-pagoda": "Pagoda Leifeng",
    "hangzhou-broken-bridge": "Puente Roto",
    "suzhou-humble-garden": "Jardín del Administrador Humilde",
    "suzhou-tiger-hill": "Colina del Tigre",
    "suzhou-pingjiang-road": "Calle Pingjiang",
    "suzhou-lingering-garden": "Jardín Liuyuan",
    "suzhou-master-nets-garden": "Jardín del Maestro de Redes",
    "suzhou-jinji-lake": "Lago Jinji",
    "suzhou-panmen-gate": "Puerta Panmen",
    "nanjing-sun-yat-sen": "Mausoleo de Sun Yat-sen",
    "nanjing-memorial-hall": "Memorial de la Masacre de Nankín",
    "nanjing-confucius-temple": "Templo de Confucio (Fuzimiao)",
    "nanjing-purple-mountain": "Montaña Púrpura",
    "nanjing-ming-wall": "Muralla de la Dinastía Ming",
    "nanjing-xuanwu-lake": "Lago Xuanwu",
    "nanjing-presidential-palace": "Palacio Presidencial",
    "nanjing-qinhuai-river": "Crucero nocturno por el río Qinhuai",
    "wuzhen-east-scenic": "Área Escénica Este de Wuzhen",
    "wuzhen-west-scenic": "Área Escénica Oeste de Wuzhen",
    "wuzhen-ancient-bridge": "Puente Antiguo",
    "wuzhen-water-town": "Crucero por el pueblo acuático",
    "wuzhen-folk-customs": "Museo de Costumbres Populares",
    "guangzhou-canton-tower": "Torre de Cantón",
    "guangzhou-temple-six-banyans": "Templo de los Seis Banyan",
    "guangzhou-shamian-island": "Isla Shamian",
    "guangzhou-yuexiu-park": "Parque Yuexiu",
    "guangzhou-pearl-river": "Crucero nocturno por el río de las Perlas",
    "guangzhou-chen-ancestral-temple": "Templo Ancestral Chen",
    "hongkong-victoria-peak": "Pico Victoria",
    "hongkong-star-ferry": "Star Ferry",
    "hongkong-disneyland": "Hong Kong Disneyland",
    "hongkong-big-buddha": "Buda Tian Tan",
    "hongkong-temple-street": "Mercado nocturno de Temple Street",
    "hongkong-ocean-park": "Ocean Park",
    "macau-ruins-st-paul": "Ruinas de San Pablo",
    "macau-venetian": "El Venetian Macao",
    "macau-a-ma-temple": "Templo A-Ma",
    "macau-senado-square": "Plaza del Senado",
    "macau-macau-tower": "Torre de Macao",
  },
  ar: {
    "beijing-great-wall": "سور الصين العظيم",
    "beijing-forbidden-city": "المدينة المحرمة",
    "beijing-temple-heaven": "معبد السماء",
    "beijing-summer-palace": "القصر الصيفي",
    "beijing-tiananmen": "ساحة تيانانمن",
    "beijing-hutong": "جولة الهوتونغ",
    "beijing-lama-temple": "معبد اللاما (يونغه)",
    "shanghai-bund": "البوند",
    "shanghai-yu-garden": "حديقة يويوان",
    "shanghai-oriental-pearl": "برج اللؤلؤة الشرقية",
    "shanghai-nanjing-road": "شارع نانجينغ",
    "shanghai-french-concession": "الامتياز الفرنسي",
    "shanghai-jade-buddha": "معبد بوذا اليشمي",
    "shanghai-disney": "شنغهاي ديزني لاند",
    "xian-terracotta": "جنود التيراكوتا",
    "xian-city-wall": "سور مدينة شيآن",
    "xian-big-wild-goose": "برج الإوزة البرية الكبيرة",
    "xian-muslim-quarter": "الحي الإسلامي",
    "xian-bell-tower": "برج الجرس",
    "guilin-li-river": "رحلة نهر لي",
    "guilin-reed-flute": "كهف الفلوت القصب",
    "guilin-elephant-trunk": "تلة خرطوم الفيل",
    "guilin-seven-star": "حديقة النجوم السبعة",
    "guilin-yangshuo": "بلدة يانغشو",
    "chengdu-panda-base": "قاعدة تشنغدو لتربية الباندا",
    "chengdu-jinli": "شارع جينلي القديم",
    "chengdu-wuhou": "ضريح ووهوو",
    "chengdu-wide-alley": "الأزقة العريضة والضيقة",
    "chengdu-dujiangyan": "نظام ري دوجيانغيان",
    "chengdu-mount-qingcheng": "جبل تشينغتشنغ",
    "chengdu-people-park": "حديقة الشعب",
    "chengdu-sichuan-opera": "عرض أوبرا سيتشوان",
    "hangzhou-west-lake": "بحيرة الغرب",
    "hangzhou-lingyin": "معبد لينغيين",
    "hangzhou-longjing": "قرية شاي لونغجينغ",
    "hangzhou-hefang": "شارع هيفانغ",
    "hangzhou-leifeng-pagoda": "برج ليفينغ",
    "hangzhou-broken-bridge": "الجسر المكسور",
    "suzhou-humble-garden": "حديقة المدير المتواضع",
    "suzhou-tiger-hill": "تل النمر",
    "suzhou-pingjiang-road": "شارع بينغجيانغ",
    "suzhou-lingering-garden": "حديقة ليويوان",
    "suzhou-master-nets-garden": "حديقة سيد الشباك",
    "suzhou-jinji-lake": "بحيرة جينجي",
    "suzhou-panmen-gate": "بوابة بانمن",
    "nanjing-sun-yat-sen": "ضريح صن يات سن",
    "nanjing-memorial-hall": "متحف مذبحة نانجينغ",
    "nanjing-confucius-temple": "معبد كونفوشيوس (فوزيمياو)",
    "nanjing-purple-mountain": "الجبل البنفسجي",
    "nanjing-ming-wall": "سور مدينة مينغ",
    "nanjing-xuanwu-lake": "بحيرة شيوان وو",
    "nanjing-presidential-palace": "القصر الرئاسي",
    "nanjing-qinhuai-river": "رحلة ليلية في نهر تشينهواي",
    "wuzhen-east-scenic": "منطقة وجن الشرقية الخلابة",
    "wuzhen-west-scenic": "منطقة وجن الغربية الخلابة",
    "wuzhen-ancient-bridge": "جسر قديم",
    "wuzhen-water-town": "رحلة في بلدة الماء",
    "wuzhen-folk-customs": "متحف العادات الشعبية",
    "guangzhou-canton-tower": "برج كانتون",
    "guangzhou-temple-six-banyans": "معبد أشجار البانيان الست",
    "guangzhou-shamian-island": "جزيرة شاميان",
    "guangzhou-yuexiu-park": "حديقة يويهسيو",
    "guangzhou-pearl-river": "رحلة ليلية في نهر اللؤلؤ",
    "guangzhou-chen-ancestral-temple": "معبد عائلة تشين",
    "hongkong-victoria-peak": "قمة فيكتوريا",
    "hongkong-star-ferry": "ستار فيري",
    "hongkong-disneyland": "ديزني لاند هونغ كونغ",
    "hongkong-big-buddha": "بوذا تيان تان",
    "hongkong-temple-street": "سوق الليل شارع تمبل",
    "hongkong-ocean-park": "أوشن بارك",
    "macau-ruins-st-paul": "أطلال سانت بول",
    "macau-venetian": "فينيسيان ماكاو",
    "macau-a-ma-temple": "معبد أما",
    "macau-senado-square": "ساحة السينادو",
    "macau-macau-tower": "برج ماكاو",
  },
  ru: {
    "beijing-great-wall": "Великая китайская стена",
    "beijing-forbidden-city": "Запретный город",
    "beijing-temple-heaven": "Храм Неба",
    "beijing-summer-palace": "Летний дворец",
    "beijing-tiananmen": "Площадь Тяньаньмэнь",
    "beijing-hutong": "Тур по хутунам",
    "beijing-lama-temple": "Храм Ламы (Юнхэгун)",
    "shanghai-bund": "Бунд",
    "shanghai-yu-garden": "Сад Юйюань",
    "shanghai-oriental-pearl": "Башня «Жемчужина Востока»",
    "shanghai-nanjing-road": "Нанкинская улица",
    "shanghai-french-concession": "Французская концессия",
    "shanghai-jade-buddha": "Храм Нефритового Будды",
    "shanghai-disney": "Шанхай Диснейленд",
    "xian-terracotta": "Терракотовые воины",
    "xian-city-wall": "Сианьская городская стена",
    "xian-big-wild-goose": "Пагода Большой дикой гусыни",
    "xian-muslim-quarter": "Мусульманский квартал",
    "xian-bell-tower": "Колокольная башня",
    "guilin-li-river": "Круиз по реке Ли",
    "guilin-reed-flute": "Пещера Свирели",
    "guilin-elephant-trunk": "Холм Слоновьего Хобота",
    "guilin-seven-star": "Парк семи звёзд",
    "guilin-yangshuo": "Город Яншо",
    "chengdu-panda-base": "База разведения панд в Чэнду",
    "chengdu-jinli": "Древняя улица Цзинли",
    "chengdu-wuhou": "Храм Ухоу",
    "chengdu-wide-alley": "Широкие и узкие переулки",
    "chengdu-dujiangyan": "Система орошения Дуцзянъянь",
    "chengdu-mount-qingcheng": "Гора Цинчэн",
    "chengdu-people-park": "Народный парк",
    "chengdu-sichuan-opera": "Представление сычуаньской оперы",
    "hangzhou-west-lake": "Западное озеро",
    "hangzhou-lingyin": "Храм Линъинь",
    "hangzhou-longjing": "Деревня чая Лунцзин",
    "hangzhou-hefang": "Улица Хэфан",
    "hangzhou-leifeng-pagoda": "Пагода Лэйфэн",
    "hangzhou-broken-bridge": "Сломанный мост",
    "suzhou-humble-garden": "Сад скромного администратора",
    "suzhou-tiger-hill": "Тигровый холм",
    "suzhou-pingjiang-road": "Улица Пинцзян",
    "suzhou-lingering-garden": "Сад Люй",
    "suzhou-master-nets-garden": "Сад мастера сетей",
    "suzhou-jinji-lake": "Озеро Цзинцзи",
    "suzhou-panmen-gate": "Ворота Паньмэнь",
    "nanjing-sun-yat-sen": "Мавзолей Сунь Ятсена",
    "nanjing-memorial-hall": "Мемориал Нанкинской резни",
    "nanjing-confucius-temple": "Храм Конфуция (Фуцзимяо)",
    "nanjing-purple-mountain": "Цзыцзиньшань",
    "nanjing-ming-wall": "Стена династии Мин",
    "nanjing-xuanwu-lake": "Озеро Сюаньу",
    "nanjing-presidential-palace": "Президентский дворец",
    "nanjing-qinhuai-river": "Ночной круиз по реке Циньхуай",
    "wuzhen-east-scenic": "Восточная живописная зона Учжэнь",
    "wuzhen-west-scenic": "Западная живописная зона Учжэнь",
    "wuzhen-ancient-bridge": "Древний мост",
    "wuzhen-water-town": "Круиз по водному городу",
    "wuzhen-folk-customs": "Музей народных обычаев",
    "guangzhou-canton-tower": "Башня Кантона",
    "guangzhou-temple-six-banyans": "Храм шести фикусов",
    "guangzhou-shamian-island": "Остров Шамянь",
    "guangzhou-yuexiu-park": "Парк Юэсю",
    "guangzhou-pearl-river": "Ночной круиз по реке Жемчужной",
    "guangzhou-chen-ancestral-temple": "Анцестральный храм Чэнь",
    "hongkong-victoria-peak": "Виктория-Пик",
    "hongkong-star-ferry": "Стар Ферри",
    "hongkong-disneyland": "Гонконг Диснейленд",
    "hongkong-big-buddha": "Тянь Тан Будда",
    "hongkong-temple-street": "Ночной рынок Темпл-стрит",
    "hongkong-ocean-park": "Оушен Парк",
    "macau-ruins-st-paul": "Руины Святого Павла",
    "macau-venetian": "Венецианец Макао",
    "macau-a-ma-temple": "Храм А-Ма",
    "macau-senado-square": "Площадь Сената",
    "macau-macau-tower": "Башня Макао",
  },
};

const MEAL_NAME_MAP: Record<Language, Record<string, string>> = {
  en: {
    "beijing-peking-duck": "Peking Duck",
    "beijing-jiaozi": "Beijing Dumplings (Jiaozi)",
    "beijing-zhajiangmian": "Zhajiangmian (Noodles)",
    "beijing-hotpot": "Beijing Hotpot",
    "shanghai-xiaolongbao": "Xiaolongbao (Soup Dumplings)",
    "shanghai-shengjianbao": "Shengjianbao (Pan-fried Buns)",
    "shanghai-hairy-crab": "Shanghai Hairy Crab",
    "shanghai-braised-pork": "Hongshao Rou (Braised Pork)",
    "xian-biang-biang": "Biang Biang Noodles",
    "xian-roujiamo": "Roujiamo (Chinese Burger)",
    "xian-yangrou-paomo": "Yangrou Paomo (Lamb Soup)",
    "xian-liangpi": "Liangpi (Cold Noodles)",
    "guilin-rice-noodles": "Guilin Rice Noodles",
    "guilin-beer-fish": "Yangshuo Beer Fish",
    "guilin-stuffed-snails": "Stuffed River Snails",
    "chengdu-hotpot": "Chengdu Spicy Hotpot",
    "chengdu-mapo-tofu": "Mapo Tofu",
    "chengdu-dan-dan": "Dan Dan Noodles",
    "chengdu-kung-pao": "Kung Pao Chicken",
    "chengdu-fuqi-feipian": "Fuqi Feipian (Beef Slices)",
    "hangzhou-west-lake-fish": "West Lake Fish in Vinegar",
    "hangzhou-dongpo-pork": "Dongpo Pork",
    "hangzhou-longjing-shrimp": "Longjing Tea Shrimp",
    "suzhou-squirrel-fish": "Squirrel-shaped Mandarin Fish",
    "suzhou-biluochun-tea": "Biluochun Tea Experience",
    "suzhou-sweet-sour-ribs": "Sweet and Sour Ribs",
    "nanjing-salted-duck": "Nanjing Salted Duck",
    "nanjing-duck-blood-soup": "Duck Blood Soup",
    "nanjing-steamed-buns": "Nanjing Soup Dumplings",
    "nanjing-beef-pot-stickers": "Beef Pot Stickers",
    "wuzhen-dongpo-pork": "Wuzhen Dongpo Pork",
    "wuzhen-white-fish": "Steamed White Fish",
    "wuzhen-wine-chicken": "Wuzhen Wine Chicken",
    "guangzhou-dim-sum": "Cantonese Dim Sum",
    "guangzhou-roast-goose": "Roast Goose",
    "guangzhou-wonton-noodles": "Wonton Noodles",
    "guangzhou-claypot-rice": "Claypot Rice",
    "hongkong-char-siu": "Char Siu (BBQ Pork)",
    "hongkong-egg-tart": "Hong Kong Egg Tart",
    "hongkong-milk-tea": "Hong Kong Style Milk Tea",
    "hongkong-wonton-soup": "Wonton Soup",
    "macau-egg-tart": "Macau Egg Tart",
    "macau-african-chicken": "African Chicken",
    "macau-pork-chop-bun": "Pork Chop Bun",
    "macau-minchi": "Minchi (Macanese Hash)",
  },
  zh: {
    "beijing-peking-duck": "北京烤鸭",
    "beijing-jiaozi": "北京饺子（饺子）",
    "beijing-zhajiangmian": "炸酱面",
    "beijing-hotpot": "北京火锅",
    "shanghai-xiaolongbao": "小笼包",
    "shanghai-shengjianbao": "生煎包",
    "shanghai-hairy-crab": "大闸蟹",
    "shanghai-braised-pork": "红烧肉",
    "xian-biang-biang": "biangbiang面",
    "xian-roujiamo": "肉夹馍",
    "xian-yangrou-paomo": "羊肉泡馍",
    "xian-liangpi": "凉皮",
    "guilin-rice-noodles": "桂林米粉",
    "guilin-beer-fish": "啤酒鱼（阳朔）",
    "guilin-stuffed-snails": "酿田螺",
    "chengdu-hotpot": "成都麻辣火锅",
    "chengdu-mapo-tofu": "麻婆豆腐",
    "chengdu-dan-dan": "担担面",
    "chengdu-kung-pao": "宫保鸡丁",
    "chengdu-fuqi-feipian": "夫妻肺片",
    "hangzhou-west-lake-fish": "西湖醋鱼",
    "hangzhou-dongpo-pork": "东坡肉",
    "hangzhou-longjing-shrimp": "龙井虾仁",
    "suzhou-squirrel-fish": "松鼠桂鱼",
    "suzhou-biluochun-tea": "碧螺春品茶体验",
    "suzhou-sweet-sour-ribs": "糖醋排骨",
    "nanjing-salted-duck": "南京盐水鸭",
    "nanjing-duck-blood-soup": "鸭血粉丝汤",
    "nanjing-steamed-buns": "南京汤包",
    "nanjing-beef-pot-stickers": "牛肉锅贴",
    "wuzhen-dongpo-pork": "乌镇东坡肉",
    "wuzhen-white-fish": "清蒸白鱼",
    "wuzhen-wine-chicken": "乌镇黄酒鸡",
    "guangzhou-dim-sum": "粤式点心",
    "guangzhou-roast-goose": "烧鹅",
    "guangzhou-wonton-noodles": "云吞面",
    "guangzhou-claypot-rice": "煲仔饭",
    "hongkong-char-siu": "叉烧",
    "hongkong-egg-tart": "港式蛋挞",
    "hongkong-milk-tea": "港式奶茶",
    "hongkong-wonton-soup": "云吞汤",
    "macau-egg-tart": "澳门蛋挞",
    "macau-african-chicken": "非洲鸡",
    "macau-pork-chop-bun": "猪扒包",
    "macau-minchi": "免治",
  },
  fr: {
    "beijing-peking-duck": "Canard laqué de Pékin",
    "beijing-jiaozi": "Raviolis de Pékin (Jiaozi)",
    "beijing-zhajiangmian": "Zhajiangmian (Nouilles)",
    "beijing-hotpot": "Fondue de Pékin",
    "shanghai-xiaolongbao": "Xiaolongbao (raviolis à la soupe)",
    "shanghai-shengjianbao": "Shengjianbao (brioches poêlées)",
    "shanghai-hairy-crab": "Crabe poilu de Shanghai",
    "shanghai-braised-pork": "Hongshao Rou (porc braisé)",
    "xian-biang-biang": "Nouilles Biang Biang",
    "xian-roujiamo": "Roujiamo (sandwich chinois)",
    "xian-yangrou-paomo": "Yangrou Paomo (soupe d'agneau)",
    "xian-liangpi": "Liangpi (nouilles froides)",
    "guilin-rice-noodles": "Nouilles de riz de Guilin",
    "guilin-beer-fish": "Poisson à la bière de Yangshuo",
    "guilin-stuffed-snails": "Escargots de rivière farcis",
    "chengdu-hotpot": "Fondue épicée de Chengdu",
    "chengdu-mapo-tofu": "Tofu Mapo",
    "chengdu-dan-dan": "Nouilles Dan Dan",
    "chengdu-kung-pao": "Poulet Kung Pao",
    "chengdu-fuqi-feipian": "Fuqi Feipian (tranches de bœuf)",
    "hangzhou-west-lake-fish": "Poisson du Lac de l'Ouest au vinaigre",
    "hangzhou-dongpo-pork": "Porc Dongpo",
    "hangzhou-longjing-shrimp": "Crevettes au thé Longjing",
    "suzhou-squirrel-fish": "Poisson mandarin en forme d'écureuil",
    "suzhou-biluochun-tea": "Expérience du thé Biluochun",
    "suzhou-sweet-sour-ribs": "Côtes de porc aigre-douce",
    "nanjing-salted-duck": "Canard salé de Nankin",
    "nanjing-duck-blood-soup": "Soupe de sang de canard",
    "nanjing-steamed-buns": "Raviolis en soupe de Nankin",
    "nanjing-beef-pot-stickers": "Raviolis grillés au bœuf",
    "wuzhen-dongpo-pork": "Porc Dongpo de Wuzhen",
    "wuzhen-white-fish": "Poisson blanc à la vapeur",
    "wuzhen-wine-chicken": "Poulet au vin de Wuzhen",
    "guangzhou-dim-sum": "Dim Sum Cantonnais",
    "guangzhou-roast-goose": "Oie rôtie",
    "guangzhou-wonton-noodles": "Nouilles wonton",
    "guangzhou-claypot-rice": "Riz en marmite",
    "hongkong-char-siu": "Char Siu (porc BBQ)",
    "hongkong-egg-tart": "Tarte aux œufs de Hong Kong",
    "hongkong-milk-tea": "Thé au lait à la Hongkongaise",
    "hongkong-wonton-soup": "Soupe wonton",
    "macau-egg-tart": "Tarte aux œufs de Macao",
    "macau-african-chicken": "Poulet Africain",
    "macau-pork-chop-bun": "Sandwich à la côtelette de porc",
    "macau-minchi": "Minchi (hachis macaïste)",
  },
  es: {
    "beijing-peking-duck": "Pato laqueado de Pekín",
    "beijing-jiaozi": "Dumplings de Pekín (Jiaozi)",
    "beijing-zhajiangmian": "Zhajiangmian (Fideos)",
    "beijing-hotpot": "Hotpot de Pekín",
    "shanghai-xiaolongbao": "Xiaolongbao (dumplings de sopa)",
    "shanghai-shengjianbao": "Shengjianbao (bollos fritos)",
    "shanghai-hairy-crab": "Cangrejo peludo de Shanghái",
    "shanghai-braised-pork": "Hongshao Rou (cerdo estofado)",
    "xian-biang-biang": "Fideos Biang Biang",
    "xian-roujiamo": "Roujiamo (hamburguesa china)",
    "xian-yangrou-paomo": "Yangrou Paomo (sopa de cordero)",
    "xian-liangpi": "Liangpi (fideos fríos)",
    "guilin-rice-noodles": "Fideos de arroz de Guilin",
    "guilin-beer-fish": "Pescado a la cerveza de Yangshuo",
    "guilin-stuffed-snails": "Caracoles de río rellenos",
    "chengdu-hotpot": "Hotpot picante de Chengdu",
    "chengdu-mapo-tofu": "Mapo Tofu",
    "chengdu-dan-dan": "Fideos Dan Dan",
    "chengdu-kung-pao": "Pollo Kung Pao",
    "chengdu-fuqi-feipian": "Fuqi Feipian (láminas de res)",
    "hangzhou-west-lake-fish": "Pescado del Lago del Oeste con vinagre",
    "hangzhou-dongpo-pork": "Cerdo Dongpo",
    "hangzhou-longjing-shrimp": "Camarones al té Longjing",
    "suzhou-squirrel-fish": "Pez mandarín con forma de ardilla",
    "suzhou-biluochun-tea": "Experiencia del té Biluochun",
    "suzhou-sweet-sour-ribs": "Costillas agridulces",
    "nanjing-salted-duck": "Pato salado de Nankín",
    "nanjing-duck-blood-soup": "Sopa de sangre de pato",
    "nanjing-steamed-buns": "Dumplings en sopa de Nankín",
    "nanjing-beef-pot-stickers": "Empanadillas de carne",
    "wuzhen-dongpo-pork": "Cerdo Dongpo de Wuzhen",
    "wuzhen-white-fish": "Pescado blanco al vapor",
    "wuzhen-wine-chicken": "Pollo al vino de Wuzhen",
    "guangzhou-dim-sum": "Dim Sum Cantonés",
    "guangzhou-roast-goose": "Ganso asado",
    "guangzhou-wonton-noodles": "Fideos wonton",
    "guangzhou-claypot-rice": "Arroz en cazuela",
    "hongkong-char-siu": "Char Siu (cerdo BBQ)",
    "hongkong-egg-tart": "Tarta de huevo de Hong Kong",
    "hongkong-milk-tea": "Té con leche estilo Hong Kong",
    "hongkong-wonton-soup": "Sopa wonton",
    "macau-egg-tart": "Tarta de huevo de Macao",
    "macau-african-chicken": "Pollo Africano",
    "macau-pork-chop-bun": "Pan de chuleta de cerdo",
    "macau-minchi": "Minchi (hash macaense)",
  },
  ar: {
    "beijing-peking-duck": "بط بكين المشوي",
    "beijing-jiaozi": "زلابية بكين (جياو تسي)",
    "beijing-zhajiangmian": "زهاجيانغ ميان (نودلز)",
    "beijing-hotpot": "هوت بوت بكين",
    "shanghai-xiaolongbao": "شياولونغباو (زلابية حساء)",
    "shanghai-shengjianbao": "شنغجيانباو (خبز مقلي)",
    "shanghai-hairy-crab": "سلطعون مشعر شنغهاي",
    "shanghai-braised-pork": "هونغشاو رو (لحم خنزير مطهو)",
    "xian-biang-biang": "معكرونة بيانغ بيانغ",
    "xian-roujiamo": "روجيا مو (برغر صيني)",
    "xian-yangrou-paomo": "يانغرو باومو (حساء لحم الضأن)",
    "xian-liangpi": "ليانغبي (نودلز بارد)",
    "guilin-rice-noodles": "نودلز الأرز قويلين",
    "guilin-beer-fish": "سمك بالبيرة في يانغشو",
    "guilin-stuffed-snails": "حلزون نهري محشو",
    "chengdu-hotpot": "هوت بوت حار تشنغدو",
    "chengdu-mapo-tofu": "توفر مابو",
    "chengdu-dan-dan": "نودلز دان دان",
    "chengdu-kung-pao": "دجاج كونغ باو",
    "chengdu-fuqi-feipian": "فو تشي فيبيان (شرائح لحم بقري)",
    "hangzhou-west-lake-fish": "سمك بحيرة الغرب بالخل",
    "hangzhou-dongpo-pork": "لحم خنزير دونغبو",
    "hangzhou-longjing-shrimp": "روبيان شاي لونغجينغ",
    "suzhou-squirrel-fish": "سمك ماندرين بشكل سنجاب",
    "suzhou-biluochun-tea": "تجربة شاي بيلوشون",
    "suzhou-sweet-sour-ribs": "ضلوع حلوة وحامضة",
    "nanjing-salted-duck": "بطة نانجينغ المالحة",
    "nanjing-duck-blood-soup": "حساء دم البط",
    "nanjing-steamed-buns": "زلابية شوربة نانجينغ",
    "nanjing-beef-pot-stickers": "زلابية لحم بقري مقلية",
    "wuzhen-dongpo-pork": "لحم دونغبو وجن",
    "wuzhen-white-fish": "سمك أبيض مطهو بالبخار",
    "wuzhen-wine-chicken": "دجاج نبيذ وجن",
    "guangzhou-dim-sum": "ديم سوم كانتوني",
    "guangzhou-roast-goose": "إوز مشوي",
    "guangzhou-wonton-noodles": "نودلز وانتون",
    "guangzhou-claypot-rice": "أرز في قدر خزفي",
    "hongkong-char-siu": "تشار سيو (لحم خنزير مشوي)",
    "hongkong-egg-tart": "فطيرة بيض هونغ كونغ",
    "hongkong-milk-tea": "شاي بالحليب على طريقة هونغ كونغ",
    "hongkong-wonton-soup": "حساء وانتون",
    "macau-egg-tart": "فطيرة بيض ماكاو",
    "macau-african-chicken": "دجاج أفريقي",
    "macau-pork-chop-bun": "سندويش كستليتة لحم خنزير",
    "macau-minchi": "مينتشي (هاش ماكاوي)",
  },
  ru: {
    "beijing-peking-duck": "Пекинская утка",
    "beijing-jiaozi": "Пекинские пельмени (цзяоцзы)",
    "beijing-zhajiangmian": "Чжачжанмянь (лапша)",
    "beijing-hotpot": "Пекинский хотпот",
    "shanghai-xiaolongbao": "Сяолунбао (суповые пельмени)",
    "shanghai-shengjianbao": "Шэнцзяньбао (жареные булочки)",
    "shanghai-hairy-crab": "Шанхайский волосатый краб",
    "shanghai-braised-pork": "Хуншао жоу (тушёная свинина)",
    "xian-biang-biang": "Лапша бянь-бянь",
    "xian-roujiamo": "Жоудзямо (китайский бургер)",
    "xian-yangrou-paomo": "Янжоу Паомо (суп из баранины)",
    "xian-liangpi": "Лянпи (холодная лапша)",
    "guilin-rice-noodles": "Гуйлиньская рисовая лапша",
    "guilin-beer-fish": "Рыба в пиве Яншо",
    "guilin-stuffed-snails": "Фаршированные речные улитки",
    "chengdu-hotpot": "Чэнду острый хотпот",
    "chengdu-mapo-tofu": "Мапо тофу",
    "chengdu-dan-dan": "Лапша дан дан",
    "chengdu-kung-pao": "Курица Кунг Пао",
    "chengdu-fuqi-feipian": "Фуци фэйпянь (ломтики говядины)",
    "hangzhou-west-lake-fish": "Рыба из Западного озера в уксусе",
    "hangzhou-dongpo-pork": "Свиная грудинка Дунпо",
    "hangzhou-longjing-shrimp": "Креветки в чае Лунцзин",
    "suzhou-squirrel-fish": "Мандариновая рыба в форме белки",
    "suzhou-biluochun-tea": "Опыт чая БиЛоЧунь",
    "suzhou-sweet-sour-ribs": "Кисло-сладкие ребрышки",
    "nanjing-salted-duck": "Нанкинская солёная утка",
    "nanjing-duck-blood-soup": "Суп из утиной крови",
    "nanjing-steamed-buns": "Нанкинские суповые пельмени",
    "nanjing-beef-pot-stickers": "Жареные пельмени с говядиной",
    "wuzhen-dongpo-pork": "Учжэньский Дунпо",
    "wuzhen-white-fish": "Паровая белая рыба",
    "wuzhen-wine-chicken": "Курица в вине Учжэнь",
    "guangzhou-dim-sum": "Кантонский димсам",
    "guangzhou-roast-goose": "Жареный гусь",
    "guangzhou-wonton-noodles": "Лапша с вонтоном",
    "guangzhou-claypot-rice": "Рис в горшочке",
    "hongkong-char-siu": "Чар сью (барбекю свинина)",
    "hongkong-egg-tart": "Гонконгский яйцевый тарт",
    "hongkong-milk-tea": "Гонконгский чай с молоком",
    "hongkong-wonton-soup": "Суп вонтон",
    "macau-egg-tart": "Макаоский яйцевый тарт",
    "macau-african-chicken": "Африканский цыплёнок",
    "macau-pork-chop-bun": "Булочка с отбивной из свинины",
    "macau-minchi": "Минчи (макао хэш)",
  },
};

export function getAttractionName(
  id: string,
  fallbackName: string,
  language: Language
): string {
  const map = ATTRACTION_NAME_MAP[language] || {};
  return map[id] || fallbackName;
}

export function getMealName(
  id: string,
  fallbackName: string,
  language: Language
): string {
  const map = MEAL_NAME_MAP[language] || {};
  return map[id] || fallbackName;
}

const INTEREST_LABEL_MAP: Record<Language, Record<string, string>> = {
  en: {
    "Historical Sites": "Historical Sites",
    "Natural Scenery": "Natural Scenery",
    "Urban Exploration": "Urban Exploration",
    "Food & Cuisine": "Food & Cuisine",
    Shopping: "Shopping",
    Adventure: "Adventure",
    "Art & Museums": "Art & Museums",
    Photography: "Photography",
    "Local Culture": "Local Culture",
    Nightlife: "Nightlife",
  },
  zh: {
    "Historical Sites": "历史古迹",
    "Natural Scenery": "自然风光",
    "Urban Exploration": "城市探索",
    "Food & Cuisine": "美食",
    Shopping: "购物",
    Adventure: "冒险",
    "Art & Museums": "艺术与博物馆",
    Photography: "摄影",
    "Local Culture": "本土文化",
    Nightlife: "夜生活",
  },
  es: {
    "Historical Sites": "Sitios históricos",
    "Natural Scenery": "Paisajes naturales",
    "Urban Exploration": "Exploración urbana",
    "Food & Cuisine": "Comida y gastronomía",
    Shopping: "Compras",
    Adventure: "Aventura",
    "Art & Museums": "Arte y museos",
    Photography: "Fotografía",
    "Local Culture": "Cultura local",
    Nightlife: "Vida nocturna",
  },
  fr: {
    "Historical Sites": "Sites historiques",
    "Natural Scenery": "Paysages naturels",
    "Urban Exploration": "Exploration urbaine",
    "Food & Cuisine": "Cuisine et gastronomie",
    Shopping: "Shopping",
    Adventure: "Aventure",
    "Art & Museums": "Art et musées",
    Photography: "Photographie",
    "Local Culture": "Culture locale",
    Nightlife: "Vie nocturne",
  },
  ar: {
    "Historical Sites": "مواقع تاريخية",
    "Natural Scenery": "مناظر طبيعية",
    "Urban Exploration": "استكشاف حضري",
    "Food & Cuisine": "طعام ومأكولات",
    Shopping: "تسوق",
    Adventure: "مغامرة",
    "Art & Museums": "فن ومتاحف",
    Photography: "تصوير فوتوغرافي",
    "Local Culture": "ثقافة محلية",
    Nightlife: "حياة ليلية",
  },
  ru: {
    "Historical Sites": "Исторические места",
    "Natural Scenery": "Природные пейзажи",
    "Urban Exploration": "Городские исследования",
    "Food & Cuisine": "Еда и кухня",
    Shopping: "Шопинг",
    Adventure: "Приключения",
    "Art & Museums": "Искусство и музеи",
    Photography: "Фотография",
    "Local Culture": "Местная культура",
    Nightlife: "Ночная жизнь",
  },
};

export function getInterestLabel(
  interestId: string,
  language: Language
): string {
  const map = INTEREST_LABEL_MAP[language] || {};
  return map[interestId] || interestId;
}

const COUNTRY_NAME_MAP: Record<Language, Record<string, string>> = {
  en: {
    US: "United States",
    GB: "United Kingdom",
    DE: "Germany",
    FR: "France",
    JP: "Japan",
    KR: "South Korea",
    AU: "Australia",
    CA: "Canada",
    ES: "Spain",
    IT: "Italy",
  },
  zh: {
    US: "美国",
    GB: "英国",
    DE: "德国",
    FR: "法国",
    JP: "日本",
    KR: "韩国",
    AU: "澳大利亚",
    CA: "加拿大",
    ES: "西班牙",
    IT: "意大利",
  },
  es: {
    US: "Estados Unidos",
    GB: "Reino Unido",
    DE: "Alemania",
    FR: "Francia",
    JP: "Japón",
    KR: "Corea del Sur",
    AU: "Australia",
    CA: "Canadá",
    ES: "España",
    IT: "Italia",
  },
  fr: {
    US: "États-Unis",
    GB: "Royaume-Uni",
    DE: "Allemagne",
    FR: "France",
    JP: "Japon",
    KR: "Corée du Sud",
    AU: "Australie",
    CA: "Canada",
    ES: "Espagne",
    IT: "Italie",
  },
  ar: {
    US: "الولايات المتحدة",
    GB: "المملكة المتحدة",
    DE: "ألمانيا",
    FR: "فرنسا",
    JP: "اليابان",
    KR: "كوريا الجنوبية",
    AU: "أستراليا",
    CA: "كندا",
    ES: "إسبانيا",
    IT: "إيطاليا",
  },
  ru: {
    US: "США",
    GB: "Великобритания",
    DE: "Германия",
    FR: "Франция",
    JP: "Япония",
    KR: "Южная Корея",
    AU: "Австралия",
    CA: "Канада",
    ES: "Испания",
    IT: "Италия",
  },
};

export function getCountryLabel(code: string, language: Language): string {
  const map = COUNTRY_NAME_MAP[language] || {};
  return map[code] || COUNTRY_NAME_MAP.en[code] || code;
}
